import LayoutProvider from "@/providers/LayoutProvider";
import NextThemeProvider from "@/providers/NextThemeProvider";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Vista Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <NextTopLoader showSpinner={false} color="#5c59e8" />
        <NextThemeProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
