import LayoutProvider from "@/providers/LayoutProvider";
import NextThemeProvider from "@/providers/NextThemeProvider";
import "@/styles/globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vista Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextThemeProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
