import LayoutProvider from "@/providers/LayoutProvider";
import NextThemeProvider from "@/providers/NextThemeProvider";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import AuthSessionProvider from "@/providers/AuthSessionProvider";

export const metadata: Metadata = {
  title: "Vista Cart",
  description: "Generated by create next app",
};

const customStyles = {
  toast: {
    fontSize: "18px",
    padding: "16px",
  },
  toastContainer: {
    maxWidth: "400px",
    height: "auto",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Toaster
          toastOptions={{ style: { fontSize: "1.5rem" } }}
          position="top-center"
          reverseOrder={false}
        />
        <NextTopLoader showSpinner={false} color="#5c59e8" />
        <AuthSessionProvider>
          <NextThemeProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </NextThemeProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
